server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/algoarena
    username: algoarena
    password: algoarena
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false